=== Neyylo/SITE_Gimon_Dugue-master-main/XML/animals.dtd
<!ENTITY % iucnredlist "(DD|LC|NT|VU|EN|CR|EW|EX)">

<!ENTITY % coreattrs "id       ID      #IMPLIED
	  class    CDATA   #IMPLIED
	  title    CDATA   #IMPLIED"
>

<!ENTITY % URI "CDATA">
<!-- a Uniform Resource Identifier, see [RFC2396] -->

<!ENTITY % Length "CDATA">
<!-- nn for pixels or nn% for percentage length -->

<!ENTITY % Text "CDATA">
<!-- used for titles etc. -->


<!ELEMENT animal (name,img,informations,links?)>
<!ATTLIST animal %coreattrs;>

<!ELEMENT name (#PCDATA)>
<!ATTLIST name %coreattrs;>

<!ELEMENT img EMPTY>
<!ATTLIST img %coreattrs; src         %URI; #REQUIRED
	  alt         %Text; #REQUIRED
	  longdesc    %URI;          #IMPLIED
	  height      %Length;       #IMPLIED
	  width       %Length;       #IMPLIED
	  >

<!ELEMENT informations (scientificname,classification,habitat,endangerment)>
<!ATTLIST informations %coreattrs;>

<!ELEMENT scientificname (#PCDATA)>
<!ATTLIST scientificname %coreattrs;>

<!ELEMENT classification (#PCDATA)>
<!ATTLIST classification %coreattrs;>

<!ELEMENT habitat (climate,location?)>
<!ATTLIST habitat %coreattrs;>

<!ELEMENT climate (#PCDATA)>
<!ATTLIST climate %coreattrs;>

<!ELEMENT location (#PCDATA|img)*>
<!ATTLIST location %coreattrs;>

<!ELEMENT endangerment EMPTY>
<!ATTLIST endangerment %coreattrs; danger %iucnredlist; #REQUIRED
	  href  %URI;   #REQUIRED>

<!ELEMENT links (link)+>
<!ATTLIST link %coreattrs;>

<!ELEMENT link EMPTY>
<!ATTLIST link %coreattrs; href  %URI;   #REQUIRED>

=== Neyylo/SITE_Gimon_Dugue-master-main/XML/Harfang_des_neiges.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE animal SYSTEM "animals.dtd">

<animal>
    <name>Harfang des neiges</name>
    <img src="D:/L1%20programmation/L1%20Web/Harfang%20neige/240px-Bubo_scandiacus_Delta_3.jpg"
        alt="Image d'Harfang des neiges" />
    <informations>
        <scientificname>Bubo scandiacus</scientificname>
        <classification>Aves</classification>
        <habitat>
            <climate>Banquise</climate>
            <location>
                <img
                    src="D:/L1%20programmation/L1%20Web/Harfang%20neige/Capture%20d’écran%202024-02-17%20145209.png"
                    alt="Localisation des Harfangs des neiges" />
            </location>
        </habitat>
        <endangerment danger="VU" href="https://www.iucnredlist.org/fr" />
    </informations>
    <links>
        <link href="https://fr.wikipedia.org/wiki/Harfang_des_neiges" />
        <link href="https://www.iucnredlist.org/fr/species/22689055/205475036" />
    </links>
</animal>

=== Neyylo/SITE_Gimon_Dugue-master-main/XML/Ours_polaire.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE animal SYSTEM "animals.dtd">

<animal>
    <name>Ours Polaire</name>
    <img src="D:/L1%20programmation/L1%20Web/polar%20bear/Polar_Bear_2004-11-15%20(1).jpg"
        alt="Image d'ours polaire" />
    <informations>
        <scientificname>Ursus maritimus</scientificname>
        <classification>Mammalia</classification>
        <habitat>
            <climate>Banquise</climate>
            <location>
                <img src="D:/L1%20programmation/L1%20Web/polar%20bear/loaction.svg"
                    alt="Localisation des Ours Polaire" />
            </location>
        </habitat>
        <endangerment danger="VU" href="https://www.iucnredlist.org/fr" />
    </informations>
    <links>
        <link href="https://fr.wikipedia.org/wiki/Ours_blanc#" />
        <link href="https://www.iucnredlist.org/fr/species/22823/14871490" />
    </links>
</animal>

=== Neyylo/SITE_Gimon_Dugue-master-main/XML/pangolin_indien.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE animal SYSTEM "animals.dtd">
<animal>
    <name>Grand pangolin d'inde</name>
    <img src="../Images/Pangolin_indien/img.jpg" alt="Image de pangolin indien"/>
    <informations>
        <scientificname>Manis crassicaudata</scientificname>
        <classification>Mammifère, pholidote, manidé</classification>
        <habitat>
            <climate>Forêts tropicales, subtropicales et riveraines</climate>
            <location>
                <img src="../Images/Pangolin_indien/map.webp" alt="Localisation des requins renards"/>
            </location>
        </habitat>
        <endangerment danger="EN" href="https://www.iucnredlist.org/fr"/>
    </informations>
    <links>
        <link href="https://fr.wikipedia.org/wiki/Grand_pangolin_d%27Inde"/>
        <link href="https://www.iucnredlist.org/fr/species/12761/123583998"/>
    </links>
</animal>

=== Neyylo/SITE_Gimon_Dugue-master-main/XML/requin_renard.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE animal SYSTEM "animals.dtd">
<animal>
    <name>Requin renard</name>
    <img src="../Images/Requin_renard/img.jpg" alt="Image de requin renard"/>
    <informations>
        <scientificname>Alopias vulpinus</scientificname>
        <classification>Poisson cartilagineux, elasmobranchii</classification>
        <habitat>
            <climate>Oceans tempérés et tropicaux</climate>
            <location>
                <img src="../Images/Requin_renard/map.webp" alt="Localisation des requins renards"/>
            </location>
        </habitat>
        <endangerment danger="VU" href="https://www.iucnredlist.org/fr"/>
    </informations>
    <links>
        <link href="https://fr.wikipedia.org/wiki/Requin-renard"/>
        <link href="https://www.iucnredlist.org/fr/species/39339/212641186"/>
        <link href="https://geerg.ca/requin-renard/"/>
    </links>
</animal>
